apiVersion: v1
kind: Pod
metadata:
  name: cka-emptydir
spec:
  volumes:
    - name: redis-backup
      emptyDir: {}
  nodeName: kubernetes-node1
  containers:
    - name: hostpath-redis
      image: kubernetes-register.xxxx.com/xxxx/redis:7.0.10
      volumeMounts:
        - name: redis-backup
          mountPath: /data