apiVersion: apps/v1
kind: Deployment
metadata:
  name: superopsmsb-nginx-web
  labels:
    app: nginx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: nginx
          image: kubernetes-register.xxxx.com/xxxx/nginx_web:v0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: superopsmsb-nginx-web
  labels:
    app: nginx-web
spec:
  type: NodePort
  selector:
    app: nginx-web
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 31080
---