apiVersion: v1
kind: Service
metadata:
  name: cka-nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cka-django-service
spec:
  selector:
    app: django
  ports:
    - name: http
      port: 8000
---