apiVersion: v1
kind: Pod
metadata:
  name: cka-pod-init-test
  labels:
    app: cka
spec:
  containers:
    - name: cka-busybox-container
      image: 10.0.10.100:8443/busybox/busybox:1.28.3
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
    - name: cka-busybox-init-service
      image: 10.0.10.100:8443/busybox/busybox:1.28.3
      command: ['sh', '-c', "until nslookup cka-busybox-init-service; do echo waiting for cka-init-service; sleep 60; done"]
    - name: cka-busybox-init-db
      image: 10.0.10.100:8443/busybox/busybox:1.28.3
      command: ['sh', '-c', "until nslookup cka-busybox-init-db; do echo waiting for cka-init-db; sleep 60; done"]