---
apiVersion: v1
kind: Service
metadata:
  name: cka-busybox-init-service
spec:
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
 name: cka-busybox-init-db
spec:
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9377