apiVersion: v1
kind: Pod
metadata:
  name: xxxx-liveness-exec
spec:
  containers:
  - name: flask-web
    image: kubernetes-register.xxxx.com/xxxx/flask_web:v0.1
    livenessProbe:
      exec:
        command: ['/bin/bash', '-c', '[ $(curl -s 127.0.0.1/liveness)" == "OK" ]']